#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 RenoSeven

"""Embed gzip-compressed assets from assets/ into include/assets.h + src/assets.cpp."""

from __future__ import annotations

import argparse
import gzip
import subprocess
import sys
import tempfile
from pathlib import Path

# --- Constants ---

ASSETS_DIR = "assets"
OUT_HEADER = "include/assets.h"
OUT_SOURCE = "src/assets.cpp"
BYTES_PER_LINE = 16

HEADER_TEMPLATE = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 RenoSeven
//
// Declares gzip-compressed web UI assets stored in PROGMEM.
// Each asset has a uint8_t[] blob and a matching _LEN constant.
//
// Auto-generated by scripts/embed_assets.py — do not edit.

#pragma once

#include <cstddef>
#include <cstdint>
#include <pgmspace.h>

"""

SOURCE_TEMPLATE = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 RenoSeven
//
// Gzip-compressed web UI assets stored in PROGMEM.
//
// Auto-generated by scripts/embed_assets.py — do not edit.

#include "assets.h"

"""

# --- Paths ---


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def script_path() -> Path:
    return Path(__file__).resolve()


def asset_dir(base: Path) -> Path:
    return base / ASSETS_DIR


# --- Discovery ---


def find_assets(base: Path) -> list[Path]:
    d = asset_dir(base)
    if not d.is_dir():
        return []
    return sorted(p for p in d.rglob("*") if p.is_file())


def symbol_name(base: Path, path: Path) -> str:
    rel = path.relative_to(asset_dir(base))
    return str(rel).upper().replace("/", "_").replace(".", "_").replace("-", "_")


# --- Staleness ---


def is_stale(base: Path, *out_paths: Path) -> bool:
    for out in out_paths:
        if not out.is_file():
            return True
    oldest = min(p.stat().st_mtime for p in out_paths)
    for path in (*find_assets(base), script_path()):
        if path.stat().st_mtime > oldest:
            return True
    return False


# --- Rendering ---


def format_byte_array(data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def render_header(base: Path, assets: list[Path]) -> str:
    parts = [HEADER_TEMPLATE, "namespace Assets {\n\n"]
    for path in assets:
        sym = symbol_name(base, path)
        rel = path.relative_to(asset_dir(base))
        parts.append(f"    extern const uint8_t {sym}[] PROGMEM;    // {rel}\n")
        parts.append(f"    extern const size_t  {sym}_LEN;\n\n")
    parts.append("} // namespace Assets\n")
    return "".join(parts)


def render_source(base: Path, assets: list[Path]) -> str:
    parts = [SOURCE_TEMPLATE, "namespace Assets {\n\n"]
    for path in assets:
        sym = symbol_name(base, path)
        rel = path.relative_to(base)
        raw_bytes = path.read_bytes()
        compressed = gzip.compress(raw_bytes, compresslevel=9)

        parts.append(f"// {rel}  ({len(raw_bytes)} -> {len(compressed)} bytes)\n")
        parts.append(f"const uint8_t {sym}[] PROGMEM = {{\n")
        parts.append(format_byte_array(compressed))
        parts.append("\n};\n")
        parts.append(f"const size_t {sym}_LEN = sizeof({sym});\n\n")

    parts.append("} // namespace Assets\n")
    return "".join(parts)


# --- File I/O ---


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.replace(path)


# --- CLI ---


def create_parser() -> argparse.ArgumentParser:
    cmd = f"./{Path(__file__).name}"
    parser = argparse.ArgumentParser(
        description="Embed gzip-compressed assets into include/assets.h and src/assets.cpp.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            f"examples:\n"
            f"  {cmd}           # regenerate when inputs are newer\n"
            f"  {cmd} --force   # always regenerate"
        ),
    )
    parser.add_argument(
        "-f", "--force", action="store_true", help="always regenerate, even when up to date"
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true", help="suppress output when assets are up to date"
    )
    return parser


def main() -> int:
    args = create_parser().parse_args()
    base = repo_root()
    h_path = base / OUT_HEADER
    cpp_path = base / OUT_SOURCE

    assets = find_assets(base)
    if not assets:
        print(f"Error: No files found in {asset_dir(base)}", file=sys.stderr)
        return 1

    if not args.force and not is_stale(base, h_path, cpp_path):
        if not args.quiet:
            for p in assets:
                print(f"{p.relative_to(base)}: up to date.", flush=True)
        return 0

    write_atomic(h_path, render_header(base, assets))
    write_atomic(cpp_path, render_source(base, assets))

    for p in assets:
        print(f"{p.relative_to(base)}: embedded.", flush=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit as exc:
        raise SystemExit(0 if exc.code is None else exc.code) from None
    except subprocess.CalledProcessError as exc:
        raise SystemExit(exc.returncode or 1) from None
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        raise SystemExit(130) from None
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1) from None
