// SPDX-License-Identifier: MIT
// Copyright (c) 2026 RenoSeven
//
// Declares gzip-compressed web UI assets stored in PROGMEM.
// Each asset has a uint8_t[] blob and a matching _LEN constant.
//
// Auto-generated by scripts/embed_assets.py — do not edit.

#pragma once

#include <cstddef>
#include <cstdint>
#include <pgmspace.h>

namespace Assets {

    extern const uint8_t INDEX_HTML[] PROGMEM;    // index.html
    extern const size_t  INDEX_HTML_LEN;

    extern const uint8_t SCRIPT_JS[] PROGMEM;    // script.js
    extern const size_t  SCRIPT_JS_LEN;

    extern const uint8_t STYLE_CSS[] PROGMEM;    // style.css
    extern const size_t  STYLE_CSS_LEN;

} // namespace Assets
